AWSTemplateFormatVersion: '2010-09-09'
Description: 'RespawnRoom Frontend Deployment Stack'

Parameters:
  DomainName:
    Type: String
    Default: respawnroom.online
    Description: Domain name for the website

  WwwDomainName:
    Type: String
    Default: www.respawnroom.online
    Description: www subdomain for the website

  CertificateArn:
    Type: String
    Default: arn:aws:acm:us-east-1:107767828459:certificate/e3fe133f-601e-479d-8ba5-4aa5b4805d52
    Description: ARN of the ACM certificate for HTTPS

  CloudFrontDistributionId:
    Type: String
    Default: E3N45BEAZR80N5
    Description: Existing CloudFront distribution ID (if already created)

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: respawnroom-frontend
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET]
            AllowedOrigins: ['*']
            MaxAge: 3000

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: CloudFrontOriginAccessIdentity
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Action: 's3:GetObject'
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'OAI for ${DomainName}'

  CloudFrontCachingDisabledPolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: CachingDisabled
        Comment: Caching is disabled
        DefaultTTL: 0
        MinTTL: 0
        MaxTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true
          HeadersConfig:
            HeaderBehavior: none
          CookiesConfig:
            CookieBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  CloudFrontAllViewerExceptHostHeaderPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: AllViewerExceptHostHeader
        Comment: Forward all viewer headers except Host
        HeadersConfig:
          HeaderBehavior: allExcept
          Headers:
            - Host
        CookiesConfig:
          CookieBehavior: all
        QueryStringsConfig:
          QueryStringBehavior: all

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
          - !Ref WwwDomainName
        Origins:
          - DomainName: !GetAtt S3Bucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
          - DomainName: kp527ouiz74fmouhq2dzzqciky0feltt.lambda-url.us-east-1.on.aws
            Id: lambda-api
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols: [TLSv1.2]
        Enabled: true
        Comment: !Sub 'CDN for ${DomainName}'
        DefaultRootObject: index.html
        OrderedCacheBehaviors:
          - PathPattern: "/graphql*"
            TargetOriginId: lambda-api
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            CachedMethods:
              - GET
              - HEAD
            CachePolicyId: !Ref CloudFrontCachingDisabledPolicy
            OriginRequestPolicyId: !Ref CloudFrontAllViewerExceptHostHeaderPolicy
          - PathPattern: "/api/*"
            TargetOriginId: lambda-api
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            CachedMethods:
              - GET
              - HEAD
            CachePolicyId: !Ref CloudFrontCachingDisabledPolicy
            OriginRequestPolicyId: !Ref CloudFrontAllViewerExceptHostHeaderPolicy
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
          Compress: true
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0

Outputs:
  WebsiteURL:
    Value: !Sub 'https://${DomainName}'
    Description: URL for website

  CloudFrontDistributionId:
    Value: !Ref CloudFrontDistribution
    Description: CloudFront distribution ID

  S3BucketName:
    Value: !Ref S3Bucket
    Description: Name of S3 bucket to upload content

  CloudFrontDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Description: CloudFront distribution domain name 