deploy:
  runs-on: ubuntu-latest
  permissions:
    deployments: write
  steps:
    - uses: JorgeLNJunior/render-deploy@v1.4.5
      with:
        service_id: ${{ secrets.dep-d0dci4h5pdvs7391m7j0 }}
        api_key: ${{ secrets.rnd_sV5S0BG1EaLgT3sYolSe4ixTc2Fh }}
        clear_cache: true # Optional: Clear Render's build cache
        wait_deploy: true
        github_deployment: true
        deployment_environment: 'production'
